apiVersion: v1
kind: Service
metadata:
  name: BitwardenServerJava
spec:
  selector:
    app: BitwardenServerJava
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  