spring:
  application:
    name: bitwarden-server-java
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, env, loggers
  endpoint:
    health:
      show-components: always
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id}, %X{span_id}]"