management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-components: always
      show-details: always
logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id}, %X{span_id}"